### ISSUE TITLE
Seaside dependency should be on the Github repository and not on STHub

### ISSUE THREAD

**Issue by jecisc** [astares/Seaside-Bootstrap#4]
The STHub repository is not maintained anymore and we cannot load this version of bootstrap in an image with Seaside from github.

**Comment by svenvc** [comment]
It would be very nice of this got integrated

**Comment by astares** [comment]
The basic problem is still that the Github version of Seaside is not working on all platforms 
as on Windows we still have the issue with long path/file names.

Johan is willing to convert Seaside to Tonel so Seaside also works on Windows again - but
currently an issue hold him back:

https://github.com/pharo-vcs/tonel/issues/74

Esteban hopefully will have the time to look into this issue soon.
