### ISSUE TITLE
jQuery conflict with latest Seaside

### ISSUE THREAD

**Issue by eftomi** [astares/Seaside-Bootstrap#9]
Hi, when running Seaside-Bootstrap application with the latest [Seaside](https://github.com/SeasideSt/Seaside) on Pharo 7.0 the browser reports:

```
Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3"
in the console. 
```

and mouse clicks won't work (as tested with Chrome, Firefox, Edge). At the same time, browser's console reports jQuery version 3.3.1 ($.fn.jquery). This is true for the bootstrap application, too.

This might be related to the issue [Bootstrap v3 is not compatible with jQuery 3.0](https://github.com/twbs/bootstrap/issues/16834) that has been resolved in Bootstrap 3.3.7.

A simple workaround is to copy&paste the Bootstrap 3.3.7 code directly into TBSDevelopmentLibrary and TBSDeploymentLibrary.

**Comment by astares** [comment]
How do you load it?

**Comment by eftomi** [comment]
I loaded Bootstrap with Catalog Browser with fresh Pharo 7.0.1 32-bit image on Windows ([other users are also reporting same experiences](http://forum.world.st/Boostrap-for-seaside-incorrect-JQuery-version-td5094996.html)). After that, if you go to localhost:8080/bootstrap/browser/Dropdowns you can directly observe the behaviour.

**Comment by astares** [comment]
Can you try loading instructions from

https://github.com/astares/Seaside-Bootstrap

(not using catalog)

**Comment by eftomi** [comment]
Loading with Metacello gives me "IceGenericError: Failed to stat file ..." related to Seaside ...

**Comment by astares** [comment]
Ahh .. OK. This is because you are on Windows (which has some problems with git projects with long file names). That's why Tonel format was invented and projects have to migrate to it (including Seaside). 

Unfortunately it is still not possible for Johan Brichau to convert latest Seaside to Tonel yet due to
an open bug in Tonel migration package:

https://github.com/pharo-vcs/tonel/issues/74

which does not seem to be of high priority yet. But if this is fixed one should be able to use it also on Windows.

**Comment by eftomi** [comment]
Yes, Windows are an obstacle here - I moved my images to c:\pharo, however it doesn't help ... I'll try to do the tests on Linux, but it will take some time.

BTW, would it be enough to just put Bootstrap 3.3.7 code to TBSDeploymentLibrary>>jsbootstrapJsContent, cssbootstrapCssContent, cssbootstrapthemeCssContent ... or are the classess in TBS packages more tightly coupled to js & css code?

**Comment by astares** [comment]
I use Linux too for the time being until Seaside works on Windows again (but more focusing on my new BS4 project than old TBS one)

You can replace the content - or if you like create custom subclasses that you register.

**Comment by eftomi** [comment]
Wow, I didn't know about BS4, this is great news!

I did two more tests on Linux:
- I loaded a fresh Pharo 7.0.1 64-bit image on Ubuntu, installed Bootstrap through Catalog Browser and the behavior is the same as before (troubles with mouse clicks, the error about jQuery incompatibility in the browser's console);
- Another fresh Pharo image, installed Bootstrap via Metacello:

```
Metacello new
  configuration:'Bootstrap';
  repository: 'github://astares/Seaside-Bootstrap:master/src';
  version: #stable;
  load

```
The result is unfortunatelly the same ...

**Comment by astares** [comment]
Updated to Bootstrap v3.3.7

https://github.com/astares/Seaside-Bootstrap/commit/f808d46932fd242ff9f45e358953e209ef71bce6

**Comment by astares** [comment]
@eftomi: checkout the project and use the "download.sh" script.

**Comment by eftomi** [comment]
It works, thank you very much!
